### ISSUE TITLE
Home Page Hospital Card is being rendered weirdly

### ISSUE THREAD

**Issue by soumalyatheking22012001** [soumalyatheking22012001/IIC-Covid-Help#124]
**Describe the bug**
When the card is rendered after returning from any route they are rendered in an erratic manner
**To Reproduce**
1. Open the Website
2. Login to your account
3. Come back to Home Page
4. Enter any search radius
5. See the card layouts in the output that comes

**Expected behavior**
Cards should be rendered in a consistent way

**Screenshots**
![image](https://user-images.githubusercontent.com/59192460/119267730-78aafa80-bc0d-11eb-97c0-174eeaba879f.png)

**Comment by afif1400** [comment]
Can I work on this?

**Comment by afif1400** [comment]
Can I work on this?

**Comment by soumalyatheking22012001** [comment]
@ra-raptor see it this cards were created by you. Of you want I would assign @afif1400 to this issue

**Comment by ra-raptor** [comment]
sure, @afif1400 can work on this issue.

According to what I have noticed, the class name "location" has conflicting styles in homePage.css and Hospitals.css, maybe because we used the same class name in two different elements, "src/components/homePage/Cards/Card.js" and in "src/components/hospitals/Hospitals.js".

Renaming any one className in their respective JSX and CSS  should solve the issue.

I guess, this is the style defination causing the unexpected behaviour of cards
![image](https://user-images.githubusercontent.com/54475223/119589030-a485d600-bdef-11eb-8bad-641a885df42e.png)

**Comment by afif1400** [comment]
> sure, @afif1400 can work on this issue.
> 
> According to what I have noticed, the class name "location" has conflicting styles in homePage.css and Hospitals.css, maybe because we used the same class name in two different elements, "src/components/homePage/Cards/Card.js" and in "src/components/hospitals/Hospitals.js".
> 
> Renaming any one className in their respective JSX and CSS should solve the issue.
> 
> I guess, this is the style defination causing the unexpected behaviour of cards
> ![image](https://user-images.githubusercontent.com/54475223/119589030-a485d600-bdef-11eb-8bad-641a885df42e.png)

Yes I'll try to fix that

**Comment by soumalyatheking22012001** [comment]
@afif1400 I assigned this issue to you

**Comment by afif1400** [comment]
@soumalyatheking22012001 not able to fetch any hospitals

**Comment by soumalyatheking22012001** [comment]
by ss I mean screenshots

**Comment by afif1400** [comment]
> can you provide more details on what error you are facing and some ss too

alright so...when I enter the radius i don't get ant response hence no card is displayed. no matter what filter I apply oxygen, vaccine, etc.

**Comment by soumalyatheking22012001** [comment]
increase the search radius may be there are no facilitates present around your location try 2000

**Comment by afif1400** [comment]
> increase the search radius may be there are no facilitates present around your location try 2000

this worked and also have fixed the issue
