### ISSUE TITLE
running the project locally.

### ISSUE THREAD

**Issue by afif1400** [soumalyatheking22012001/IIC-Covid-Help#126]
Could you put the steps to run this in a local environment, because only I see is a loading spinner on every page.

**Comment by soumalyatheking22012001** [comment]
Sorry for the inconvenience, I have clearly mentioned all the steps in the `CONTRIBUTING.md`

**Comment by soumalyatheking22012001** [comment]
If you would need any other changes please feel free to leave a comment in this thread or I will close it after a week
